---
title: "compare_3cats"
author: "Kerri M Malone"
date: "2024-03-14"
output: html_document
---


```{r setup, include=FALSE}


libs_load <- function(x){
  for( i in x ){
    print(paste0("Checking for library: ", i))
    if(require( i , character.only = TRUE ) ){
      print(paste0(i, " already installed. Loading now"))
    }
    #  require returns TRUE invisibly if it was able to load package
    if( ! require( i , character.only = TRUE ) ){
      print(paste0(i, " not installed. Trying CRAN for install."))
      #  If package was not able to be loaded then re-install
      install.packages( i , dependencies = TRUE )
      require( i , character.only = TRUE )
      paste0(i, " installed and loaded successfully")
    }
    if ( ! require(i, character.only=TRUE) ) {
      paste0(i," could not be installed from CRAN. Trying Bionconductor....")
      BiocManager::install(i)
      require( i , character.only = TRUE )
      paste0(i, " installed and loaded successfully")
    }
    if ( ! require(i, character.only=TRUE) ) {
      paste0(i, "could not be installed. Check manually")
    }
    #  Load package after installing
  }
}

#Load libraries
libs_load(c("data.table", "tidyverse", "jsonlite", "ggvenn", "ggpubr",
            "reshape2"))

`%notin%` <- Negate(`%in%`)
```


Load in stats file.  
File has been pre-filtered to only contain data for drugs that are present in all 2 cats
```{r}
d = fread("/github/cryptic-catalogue/data/training/results/compare_stats_3cats.csv")
```


```{r}
# Vector to order by
order_vector <- c("rifampicin","isoniazid", "ethambutol", "streptomycin",
                  "amikacin", "kanamycin", "capreomycin",
                  "levofloxacin", "moxifloxacin",
                  "delamanid")




g1_dat = d %>%
  select(drug, sensitive, resistant) %>%
  distinct() %>%
  pivot_longer(., !drug, names_to = "phenotype", values_to = "count")
  
g1_dat$drug <- factor(g1_dat$drug, levels = rev(order_vector))


g1 = ggplot(g1_dat, aes(y = drug, x = count, fill = phenotype)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_bw() +
  ylab("") +
  theme(panel.grid = element_blank(),
        aspect.ratio = 1)




```

Second graphs will be two barcharts showing performance (sens and spec) per catalogue for training set.  

```{r}

g2_dat = d %>%
  select(-resistant, -sensitive) %>%
  filter(catalogue != "WHOv1.2")

g2_dat$drug <- factor(g2_dat$drug, levels = rev(order_vector))

my_cols <- c("new" = "aquamarine4", "WHOv1.2" = "hotpink4", "WHOv2" = "goldenrod2")

#Create custom legend for coverage
config <- tibble::tribble(
    ~ x, ~ y, ~ s, ~ t,
    1, 1, 1, "Coverage"
)
lcol <- "black"
adj = 0.1


legend = ggplot(config, aes(x, y)) +
    geom_point(size = 2.5, show.legend = FALSE, colour = "black", shape =21) +
    scale_size_continuous(range = c(2, 4)) +
    coord_cartesian(ylim = c(1 - adj, 1 + adj)) +
    geom_text(aes(x = x, y =y +0.09, label = t), size = 4, col = lcol) +
    geom_line(lwd = 2, col = lcol) +
    theme_void()


#Specificity
g2_spec = ggplot(g2_dat, aes(y = drug, x = specificity, fill = catalogue)) +
    geom_col(colour="black",width=0.5,    
             position=position_dodge(0.5), alpha = 0.7) +
    geom_point(aes(x = coverage), position = position_dodge(width = 0.5), size = 3, colour = "black", shape = 21, show.legend = FALSE) + 
    scale_fill_manual(values = my_cols) + 
    theme_bw() +
    ylab("") +
    theme(panel.grid = element_blank(),
          aspect.ratio = 2,
          axis.ticks.y = element_blank(),
          axis.text.y = element_text(hjust = 0.5, size = 12),
          axis.text.x = element_text(angle=45, vjust=0.5)) +
    geom_vline(xintercept = seq(0, 1, by = 0.1), linetype = "dotted", color = "grey50") +
    scale_x_continuous(breaks = seq(0, 1, by = 0.05), labels = seq(0,1, by = 0.05)) +
    guides(fill = guide_legend(title = "Catalogue")) +
    labs(fill = "Catalogue") +
    scale_y_discrete(expand = expansion(mult = c(0.015,0.015)))




#add custom legend
g2_spec = g2_spec +
    annotation_custom(
        ggplotGrob(legend),
        xmin = 1,
        xmax = 1.45,
        ymin = 3,
        ymax = 3.75
    )

sens_labels = c(1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00)
#sensitivity
g2_sens = ggplot(g2_dat, aes(y = drug, x = sensitivity * -1 , fill = catalogue)) +
  geom_col(colour="black", width=0.5, position=position_dodge(0.5), alpha = 0.7) +
  geom_point(aes(x = coverage * -1), position = position_dodge(width = 0.5), size = 3, colour = "black", shape = 21, show.legend = FALSE) + 
  scale_fill_manual(values = my_cols) + 
  theme_bw() +
  ylab("") +
  theme(panel.grid = element_blank(),
        aspect.ratio = 2,
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 0.5)) +
  geom_vline(xintercept = seq(-1, 0, by = 0.1), linetype = "dotted", color = "grey50") +
  scale_x_continuous(breaks = seq(-1, 0, by = 0.05), labels = sens_labels) +  
  guides(fill = guide_legend(title = "Catalogue")) +
  labs(fill = "Catalogue") +
  scale_y_discrete(expand = expansion(mult = c(0.015,0.015))) +
  theme(legend.position = "none") +
  xlab("sensitivity")


```

FQ barcharts
```{r}
# fq = fread("/github/cryptic-catalogue/data/training/results/compare_stats_3cats_FQ_FRS.csv")
# 
# 
# 
# fq_spec = ggplot(fq, aes(y = drug, x = specificity, fill = catalogue)) +
#     geom_col(colour="black",width=0.5,    
#              position=position_dodge(0.5), alpha = 0.7) +
#     geom_point(aes(x = coverage), position = position_dodge(width = 0.5), size = 3, colour = "black", shape = 21, show.legend = FALSE) + 
#     scale_fill_manual(values = my_colors) + 
#     theme_bw() +
#     ylab("") +
#     theme(panel.grid = element_blank(),
#           aspect.ratio = 0.75,
#           axis.ticks.y = element_blank(),
#           axis.text.y = element_text(hjust = 0.5, size = 12)) +
#     geom_vline(xintercept = seq(0, max(g2_dat$specificity), by = 0.1), linetype = "dotted", color = "grey50") +
#     scale_x_continuous(breaks = seq(0, max(g2_dat$specificity), by = 0.1), labels = seq(0,1, by = 0.1)) +
#     guides(fill = guide_legend(title = "Catalogue")) +
#     labs(fill = "Catalogue") +
#     scale_y_discrete(expand = expansion(mult = c(0.015,0.015)))+
#     facet_grid(~FRS, scales = "free") +
#   theme(panel.grid = element_blank(),
#         strip.text = element_text(color = "black"),
#         strip.background = element_rect(fill = "white")) +
#   theme(legend.position = "none") 
# 
# 
# 
# 
# 
# 
# fq_sens = ggplot(fq, aes(y = drug, x = sensitivity * -1 , fill = catalogue)) +
#   geom_col(colour="black", width=0.5, 
#            position=position_dodge(0.5), alpha = 0.7) +
#   geom_point(aes(x = coverage * -1), position = position_dodge(width = 0.5), size = 3, colour = "black", shape = 21, show.legend = FALSE) + 
#   scale_fill_manual(values = my_colors) + 
#   theme_bw() +
#   ylab("") +
#   theme(panel.grid = element_blank(),
#         aspect.ratio = 0.75,
#         axis.text.y = element_text(hjust = 0.5, size = 12, colour = "white"),
#         axis.ticks.y = element_blank()) +
#   geom_vline(xintercept = seq(-1, 0, by = 0.1), linetype = "dotted", color = "grey50") +
#   scale_x_continuous(breaks = seq(-1, 0, by = 0.1), labels = seq(1.0, 0, by = -0.1)) +  
#   guides(fill = guide_legend(title = "Catalogue")) +
#   labs(fill = "Catalogue") +
#   scale_y_discrete(expand = expansion(mult = c(0.015,0.015))) +
#   theme(legend.position = "none") +
#   xlab("sensitivity")+
#     facet_grid(~FRS, scales = "free") +
#   theme(panel.grid = element_blank(),
#         strip.text = element_text(color = "black"),
#         strip.background = element_rect(fill = "white")) 

```


Validation dataset
```{r}
d = fread("/github/cryptic-catalogue/data/validation/all_catalogue_validation_stats_202406.csv")
```


Second graphs will be two barcharts showing performance (sens and spec) per catalogue for validation set.  

```{r}

g2_dat = d %>%
  select(catalogue, drug, sensitivity, specificity, coverage) %>%
  filter(catalogue != "WHOv1.2") %>%
  filter(drug %notin% c("bedaquiline", "clofazimine","ethionamide" ,"ofloxacin", "pyrazinamide", "linezolid")) %>%
  filter(!is.na(drug))

g2_dat$drug <- factor(g2_dat$drug, levels = rev(order_vector))

my_cols <- c("new" = "aquamarine4", "WHOv1.2" = "hotpink4", "WHOv2" = "goldenrod2")

#Create custom legend for coverage
config <- tibble::tribble(
    ~ x, ~ y, ~ s, ~ t,
    1, 1, 1, "Coverage"
)
lcol <- "black"
adj = 0.1


legend = ggplot(config, aes(x, y)) +
    geom_point(size = 2.5, show.legend = FALSE, colour = "black", shape =21) +
    scale_size_continuous(range = c(2, 4)) +
    coord_cartesian(ylim = c(1 - adj, 1 + adj)) +
    geom_text(aes(x = x, y =y +0.09, label = t), size = 4, col = lcol) +
    geom_line(lwd = 2, col = lcol) +
    theme_void()


#Specificity
g2_spec = ggplot(g2_dat, aes(y = drug, x = specificity, fill = catalogue)) +
    geom_col(colour="black",width=0.5,    
             position=position_dodge(0.5), alpha = 0.7) +
    geom_point(aes(x = coverage), position = position_dodge(width = 0.5), size = 3, colour = "black", shape = 21, show.legend = FALSE) + 
    scale_fill_manual(values = my_cols) + 
    theme_bw() +
    ylab("") +
    theme(panel.grid = element_blank(),
          aspect.ratio = 2,
          axis.ticks.y = element_blank(),
          axis.text.y = element_text(hjust = 0.5, size = 12),
          axis.text.x = element_text(angle=45, vjust=0.5)) +
    geom_vline(xintercept = seq(0, 1, by = 0.1), linetype = "dotted", color = "grey50") +
    scale_x_continuous(breaks = seq(0, 1, by = 0.05), labels = seq(0,1, by = 0.05)) +
    guides(fill = guide_legend(title = "Catalogue")) +
    labs(fill = "Catalogue") +
    scale_y_discrete(expand = expansion(mult = c(0.015,0.015)))




#add custom legend
g2_spec = g2_spec +
    annotation_custom(
        ggplotGrob(legend),
        xmin = 1,
        xmax = 1.45,
        ymin = 3,
        ymax = 3.75
    )

sens_labels = c(1.00, 0.95, 0.90, 0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00)
#sensitivity
g2_sens = ggplot(g2_dat, aes(y = drug, x = sensitivity * -1 , fill = catalogue)) +
  geom_col(colour="black", width=0.5, position=position_dodge(0.5), alpha = 0.7) +
  geom_point(aes(x = coverage * -1), position = position_dodge(width = 0.5), size = 3, colour = "black", shape = 21, show.legend = FALSE) + 
  scale_fill_manual(values = my_cols) + 
  theme_bw() +
  ylab("") +
  theme(panel.grid = element_blank(),
        aspect.ratio = 2,
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 0.5)) +
  geom_vline(xintercept = seq(-1, 0, by = 0.1), linetype = "dotted", color = "grey50") +
  scale_x_continuous(breaks = seq(-1, 0, by = 0.05), labels = sens_labels) +  
  guides(fill = guide_legend(title = "Catalogue")) +
  labs(fill = "Catalogue") +
  scale_y_discrete(expand = expansion(mult = c(0.015,0.015))) +
  theme(legend.position = "none") +
  xlab("sensitivity")


```
