---
title: "compare_WHO_custom_cat_venns"
author: "Kerri M Malone"
date: "2024-02-29"
output: html_document
---

```{r setup, include=FALSE}


libs_load <- function(x){
  for( i in x ){
    print(paste0("Checking for library: ", i))
    if(require( i , character.only = TRUE ) ){
      print(paste0(i, " already installed. Loading now"))
    }
    #  require returns TRUE invisibly if it was able to load package
    if( ! require( i , character.only = TRUE ) ){
      print(paste0(i, " not installed. Trying CRAN for install."))
      #  If package was not able to be loaded then re-install
      install.packages( i , dependencies = TRUE )
      require( i , character.only = TRUE )
      paste0(i, " installed and loaded successfully")
    }
    if ( ! require(i, character.only=TRUE) ) {
      paste0(i," could not be installed from CRAN. Trying Bionconductor....")
      BiocManager::install(i)
      require( i , character.only = TRUE )
      paste0(i, " installed and loaded successfully")
    }
    if ( ! require(i, character.only=TRUE) ) {
      paste0(i, "could not be installed. Check manually")
    }
    #  Load package after installing
  }
}

#Load libraries
libs_load(c("data.table", "tidyverse", "jsonlite", "ggvenn", "ggpubr"))

`%notin%` <- Negate(`%in%`)
```


Load in the catalogues for comparison

```{r}
WHO = fread("/Users/kmalone/macbook_m1_backup/github/cryptic-catalogue/data/NC_000962.3_WHO-UCN-TB-2023.5_v2.0_GARC1_RFUS.csv")
training = fread("/Users/kmalone/macbook_m1_backup/github/cryptic-catalogue/data/training/results/catomatic_training/training_catalogue_1.1_202406.csv")
drug_codes =fromJSON('/Users/kmalone/macbook_m1_backup/github/cryptic-catalogue/data/drug_codes.json')

```

Overlap and have a look at differences between MUTATION by DRUG
```{r}

venn_plot_list = list()
for (this_drug in unique(training$DRUG)) {
    this_drug_short <- drug_codes[[this_drug]]
    print(paste0("on ", this_drug, ", ", this_drug_short))
    training_mutations = training %>%
      filter(DRUG == this_drug) %>%
      select(MUTATION)  
      
    WHO_mutations = WHO %>%
      filter(DRUG == this_drug_short) %>%
      select(MUTATION)
    

    this_venn_plot <- ggvenn(data = list(training = training_mutations$MUTATION, WHO_v1.2 = WHO_mutations$MUTATION),
                            text_size = 3,
                            set_name_size = 3) + 
      scale_fill_manual(values = c("grey", "white")) + 
      labs(title = this_drug_short) +   
      theme(plot.title = element_text(hjust = 0.5, size = 12))

    venn_plot_list[[this_drug]] = this_venn_plot
    
}
  

ggarrange(plotlist = venn_plot_list, ncol = 3, nrow = 5)


```

By R/S/U counts:  

```{r}
training_freq = training %>%
    mutate(contingency = str_split(EVIDENCE, 'contingency\\"\\"\\:\\ ') %>% 
               map_chr(~ .x[2]) %>%
               map_chr(~ ifelse(length(.) == 0, NA, .))) %>%
    mutate(contingency = str_remove_all(contingency, "[\\[\\]\\}]"))  %>%
    mutate(solo_R = str_split(contingency, ", ") %>% 
               map_chr(~ if(length(.x) >= 1) .x[1] else NA)) %>%
    mutate(solo_S = str_split(contingency, ",") %>% 
               map_chr(~ if(length(.x) >= 2) .x[2] else NA)) %>%
    mutate(background_S = str_split(contingency, ",") %>% 
               map_chr(~ if(length(.x) >= 3) .x[3] else NA)) %>%
    mutate(background_R = str_split(contingency, ",") %>% 
               map_chr(~ if(length(.x) >= 4) .x[4] else NA)) %>%
    mutate(p_value = str_extract(EVIDENCE, '(?<=""p_value"": )[0-9.]+'))

#WHOv1.2
# WHO_freq = WHO %>%
#   filter(!grepl("Resistant", EVIDENCE)) %>%
#     mutate(solo_R = str_split(EVIDENCE, '\\, ') %>% 
#                map_chr(~ .x[1]) %>%
#                map_chr(~ ifelse(length(.) == 0, NA, .))) %>%
#     mutate(solo_R = str_split(solo_R, '\\:\\ ') %>% 
#                map_chr(~ .x[2]) %>%
#                map_chr(~ ifelse(length(.) == 0, NA, .))) %>%
#     mutate(solo_SR = str_split(EVIDENCE, '\\, ') %>% 
#                map_chr(~ .x[2]) %>%
#                map_chr(~ ifelse(length(.) == 0, NA, .))) %>%
#     mutate(solo_SR = str_split(solo_SR, '\\:\\ ') %>% 
#                map_chr(~ .x[2]) %>%
#                map_chr(~ ifelse(length(.) == 0, NA, .))) %>%
#     mutate(solo_S = as.numeric(solo_SR) - as.numeric(solo_R)) %>%
#   mutate(solo_S = ifelse(solo_S < 1, 0, solo_S)) %>%
#     mutate(background_R = str_split(EVIDENCE, '\\, ') %>% 
#                map_chr(~ .x[5]) %>%
#                map_chr(~ ifelse(length(.) == 0, NA, .))) %>%
#     mutate(background_R = str_split(background_R, '\\:\\ ') %>% 
#                map_chr(~ .x[2]) %>%
#                map_chr(~ ifelse(length(.) == 0, NA, .)))  %>%
#     mutate(background_S = str_split(EVIDENCE, '\\, ') %>% 
#                map_chr(~ .x[3]) %>%
#                map_chr(~ ifelse(length(.) == 0, NA, .))) %>%
#     mutate(background_S = str_split(background_S, '\\:\\ ') %>% 
#                map_chr(~ .x[2]) %>%
#                map_chr(~ ifelse(length(.) == 0, NA, .))) 

#WHOv2
WHO_freq = WHO %>%
  filter(!grepl("Resistant", EVIDENCE)) %>%
    mutate(solo_R = str_split(EVIDENCE, '\\, ') %>% 
               map_chr(~ .x[2]) %>%
               map_chr(~ ifelse(length(.) == 0, NA, .))) %>%
    mutate(solo_R = str_split(solo_R, '\\:\\ ') %>% 
               map_chr(~ .x[2]) %>%
               map_chr(~ ifelse(length(.) == 0, NA, .))) %>%
    mutate(solo_SR = str_split(EVIDENCE, '\\, ') %>% 
               map_chr(~ .x[1]) %>%
               map_chr(~ ifelse(length(.) == 0, NA, .))) %>%
    mutate(solo_SR = str_split(solo_SR, '\\:\\ ') %>% 
               map_chr(~ .x[3]) %>%
               map_chr(~ ifelse(length(.) == 0, NA, .))) %>%
    mutate(solo_S = as.numeric(solo_SR) - as.numeric(solo_R)) %>%
  mutate(solo_S = ifelse(solo_S < 1, 0, solo_S)) 
```


```{r}
prediction_cols = as.data.frame(cbind(pred_string = c("R.R", "S.S","R.S", "S.R",
                                                "U.R", "U.S","R.U", "S.U",
                                                "U.U", "S.X", "R.X", "U.X"),
                                colours = c("red", "green", "orange",
                                         "orange", "black", "darkgreen",
                                         "black", "darkgreen",
                                         "darkgrey",
                                         "lightgreen","lightpink", "lightgrey")))

prediction_cols = prediction_cols %>%
  arrange(pred_string)

problem_drug = c()
problem_mutation = c()
these_plots_match = list()
these_plots_unmatch = list()


this_top_df_training =  data.frame(DRUG= c(), 
                          comparision= c(),
                          MUTATION= c(), 
                          MATCH= c(), 
                          PREDICTION= c(), 
                          x= c(), 
                          y= c())

for (this_drug in unique(training$DRUG)) {
  if(this_drug %in% c("ciprofloxacin", "ofloxacin")){
    print("skipping")
    next
  }
  this_drug_short <- drug_codes[[this_drug]]
  print(paste0("on ", this_drug, ", ", this_drug_short))
  this_training_data = training_freq %>%
    filter(DRUG == this_drug)
  
  this_who_data = WHO_freq %>%
    filter(DRUG == this_drug_short)
 
  mutation = c()
  match = c()
  pred_strings = c()
  x = c()
  y = c()
  
  for (this_mutation in unique(this_training_data$MUTATION)){
    mutation = c(mutation, this_mutation)
    this_match = this_mutation %in% this_who_data$MUTATION
    match = c(match, this_match)
    
    if (this_match == TRUE) {
      #print(paste0("Match for mutation ", this_mutation))
      training_pred = this_training_data %>%
        filter(MUTATION == this_mutation) %>%
        pull(PREDICTION)
      
      who_pred = this_who_data %>%
        filter(MUTATION == this_mutation) %>%
        pull(PREDICTION)  
      
      if(length(who_pred) > 1){
        print(paste0("Problem with WHO entry for ", this_mutation))
        who_pred = who_pred[who_pred != "U"][1]
        problem_drug = c(problem_drug, this_drug_short)
        problem_mutation = c(problem_mutation, this_mutation)
      }
      this_pred_string = paste0(training_pred, ".", who_pred)
      pred_strings = c(pred_strings, this_pred_string)
      
      if (training_pred == "R"){
        this_x = this_training_data %>%
          filter(MUTATION == this_mutation) %>%
          pull(solo_R) 
        }
      if (training_pred == "S"){
        this_x = this_training_data %>%
          filter(MUTATION == this_mutation) %>%
          pull(solo_S) 
      }
      if (training_pred == "U"){
        this_x = this_training_data %>% 
          filter(MUTATION == this_mutation) %>% 
          mutate(choice = ifelse(as.numeric(solo_R) > as.numeric(solo_S), solo_R, solo_S)) %>%
          pull(choice)
      } 
      if (who_pred == "R"){
       this_y = this_who_data %>%
          filter(MUTATION == this_mutation) %>%
          filter(PREDICTION == who_pred) %>%
          #pull(background_R) %>%
          pull(solo_R) %>%
         unique() %>%
         head(1)
        }
      if (who_pred == "S"){
        this_y = this_who_data %>%
          filter(MUTATION == this_mutation) %>%
          filter(PREDICTION == who_pred) %>%
          #pull(background_S) %>%
          pull(solo_S) %>%
          unique() %>%
         head(1)
      }
      if (who_pred == "U"){
        this_y = this_who_data %>% 
          filter(MUTATION == this_mutation) %>% 
          filter(PREDICTION == who_pred) %>%
          #mutate(choice = ifelse(as.numeric(background_R) > as.numeric(background_S), background_R, background_S)) %>%
          mutate(choice = ifelse(as.numeric(solo_R) > as.numeric(solo_S), solo_R, solo_S)) %>%
          pull(choice) %>%
          unique() %>%
         head(1)
      } 
      if (is.na(this_x)){
        this_x = 0
      }
      if (is.na(this_y)){
        this_y = 0
      }
      x = c(x,this_x)
      y = c(y, this_y)
    }
    if(this_match == FALSE){
      #print(paste0("No match for mutation ", this_mutation))
      training_pred = this_training_data %>%
        filter(MUTATION == this_mutation) %>%
        pull(PREDICTION)      
    
      this_pred_string = paste0(training_pred, ".X")
      pred_strings = c(pred_strings, this_pred_string)
      
      if (training_pred == "R"){
        this_x = this_training_data %>%
          filter(MUTATION == this_mutation) %>%
          pull(solo_R) 
        }
      if (training_pred == "S"){
        this_x = this_training_data %>%
          filter(MUTATION == this_mutation) %>%
          pull(solo_S) 
      }
      if (training_pred == "U"){
        this_x = this_training_data %>% 
          filter(MUTATION == this_mutation) %>% 
          mutate(choice = ifelse(as.numeric(solo_R) > as.numeric(solo_S), solo_R, solo_S)) %>%
          pull(choice)
      } 
      if (is.na(this_x)){
        this_x = 0
      }
      this_y = 0
      x = c(x,this_x)
      y = c(y, this_y)
    }
  }
  this_df = as.data.frame(cbind(DRUG = c(rep(this_drug, length(pred_strings))), 
                          comparision = c(rep("training-v-WHO", length(pred_strings))),
                          MUTATION = mutation, 
                          MATCH = match, 
                          PREDICTION = pred_strings, 
                          x = as.numeric(as.character(x)), 
                          y =as.numeric(as.character(y))))

  fill_colors <- setNames(prediction_cols$colours, prediction_cols$pred_string)
  jit_lim = log(as.numeric(max(this_df$x))+1)/20


  this_plot = this_df %>%
  filter(MATCH == TRUE) %>%
  ggplot(., aes(x = log(as.numeric(x))+1, y = log(as.numeric(y))+1)) +
    geom_jitter(aes(colour = PREDICTION),size = 3, alpha = 0.5, width = jit_lim, height = 0.5) +
    scale_shape_manual(values = c(16)) +
    scale_colour_manual(values = fill_colors) +
    labs(x = "log(training isolate count) + 1", y = "log(WHOv2.0 isolate count) + 1", colour = "training.WHOv2.0") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    guides(fill = guide_legend(title = "Prediction"), shape = guide_legend(title = "Match")) +
    theme_light() +
    ggtitle(this_drug_short) +   
      theme(plot.title = element_text(hjust = 0.5, size = 12))
  
  these_plots_match[[this_drug_short]] = this_plot
  
  this_plot = this_df %>%
  filter(MATCH == FALSE) %>%
  ggplot(.,aes(x = log(as.numeric(x))+1, y = log(as.numeric(y))+1)) +
    geom_jitter(aes(colour = PREDICTION),size = 3, alpha = 0.5, width = jit_lim, height = 0.5) +
    scale_shape_manual(values = c(16)) +
    scale_colour_manual(values = fill_colors) +
    labs(x = "log(training isolate count) + 1", y = "log(WHOv2.0 isolate count) + 1", colour = "training.WHOv2.0") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    guides(fill = guide_legend(title = "Prediction"), shape = guide_legend(title = "Match")) +
    theme_light() +
    ggtitle(this_drug_short) +   
      theme(plot.title = element_text(hjust = 0.5, size = 12))
  
  these_plots_unmatch[[this_drug_short]] = this_plot
  
  this_top_df = this_df %>%
    filter(as.numeric(x) > 10) %>%
    arrange(desc(as.numeric(x)), PREDICTION)
 
  this_top_df_training = rbind(this_top_df_training, this_top_df) 
  
 
}      

ggarrange(plotlist = these_plots_match[1:4])
ggarrange(plotlist = these_plots_match[5:8])
ggarrange(plotlist = these_plots_match[9:12])

these_plots_match_training = these_plots_match
these_plots_unmatch_training = these_plots_unmatch


top_table_training = as.data.frame.matrix(table(this_top_df_training$DRUG, this_top_df_training$PREDICTION)) %>%mutate(total = rowSums(.))
write.csv(top_table_training, file = "/Users/kmalone/macbook_m1_backup/github/cryptic-catalogue/data/training/results/catomatic_training/compare_top_mutations_training_WHOv2.0_catomatic_training.csv", quote=F, row.names=T)


this_top_df_training = this_top_df_training %>% 
  mutate(filt = as.numeric(x) + as.numeric(y)) %>%
  rename("training" = x) %>%
  rename("WHOv2" = y)

write.csv(this_top_df_training, file = "/Users/kmalone/macbook_m1_backup/github/cryptic-catalogue/data/training/results/catomatic_training/compare_counts_top_mutations_training_WHOv2.0_catomatic_training.csv", quote=F, row.names=T)


```







```{r}
#### #### #### #### #### #### #### #### #### #### WHO
these_plots_match = list()
these_plots_unmatch = list()

this_top_df_who =  data.frame(DRUG= c(), 
                          comparision= c(),
                          MUTATION= c(), 
                          MATCH= c(), 
                          PREDICTION= c(), 
                          x= c(), 
                          y= c())

total_mutations = c()

for (this_drug in sort(unique(WHO$DRUG))) {
  if(this_drug %in% c("PZA", "BDQ", "CFZ")) {
    print("skipping")
    next
  }
  this_drug_short <- names(which(drug_codes == this_drug))
  print(paste0("on ", this_drug, ", ", this_drug_short))
  
  this_training_data = training_freq %>%
    filter(DRUG == this_drug_short)
  
  this_who_data = WHO_freq %>%
    filter(DRUG == this_drug)
 
  mutation = c()
  match = c()
  pred_strings = c()
  x = c()
  y = c()
  
  print(paste0("The number of unique mutations for ", this_drug, " is ", length(unique(this_who_data$MUTATION))))
  
  total_mutations = c(total_mutations, length(unique(this_who_data$MUTATION)))
  for (this_mutation in unique(this_who_data$MUTATION)){
    mutation = c(mutation, this_mutation)
    this_match = this_mutation %in% this_training_data$MUTATION
    match = c(match, this_match)
    
    if (this_match == TRUE) {
      #print(paste0("Match for mutation ", this_mutation))
      training_pred = this_training_data %>%
        filter(MUTATION == this_mutation) %>%
        pull(PREDICTION)
      
      who_pred = this_who_data %>%
        filter(MUTATION == this_mutation) %>%
        pull(PREDICTION) %>%
        head(1)  
      
      if(length(who_pred) > 1) {
        print(paste0("Problem with WHO entry for ", this_mutation))
        who_pred = who_pred[who_pred != "U"][1]
        problem_drug = c(problem_drug, this_drug_short)
        problem_mutation = c(problem_mutation, this_mutation)
      }
      this_pred_string = paste0(who_pred, ".", training_pred)
      pred_strings = c(pred_strings, this_pred_string)
      
      if (training_pred == "R"){
        this_y = this_training_data %>%
          filter(MUTATION == this_mutation) %>%
          pull(solo_R) 
        }
      if (training_pred == "S"){
        this_y = this_training_data %>%
          filter(MUTATION == this_mutation) %>%
          pull(solo_S) 
      }
      if (training_pred == "U"){
        this_y = this_training_data %>% 
          filter(MUTATION == this_mutation) %>% 
          mutate(choice = ifelse(as.numeric(solo_R) > as.numeric(solo_S), solo_R, solo_S)) %>%
          pull(choice)
      } 
      if (who_pred == "R"){
       this_x = this_who_data %>%
          filter(MUTATION == this_mutation) %>%
          filter(PREDICTION == who_pred) %>%
          pull(solo_R) %>%
          unique() %>%
         head(1)
        }
      if (who_pred == "S"){
        this_x = this_who_data %>%
          filter(MUTATION == this_mutation) %>%
          filter(PREDICTION == who_pred) %>%
          pull(solo_S) %>%
          unique()%>%
         head(1)
      }
      if (who_pred == "U"){
        this_x = this_who_data %>% 
          filter(MUTATION == this_mutation) %>% 
          filter(PREDICTION == who_pred) %>%
          mutate(choice = ifelse(as.numeric(solo_R) > as.numeric(solo_S), solo_R, solo_S)) %>%
          pull(choice) %>%
          unique() %>%
         head(1)
      } 
      if (is.na(this_y)){
        this_y = 0
      }
      if (is.na(this_x)){
        this_x = 0
      }
      x = c(x,this_x)
      y = c(y, this_y)
    }
    if(this_match == FALSE) {
      #print(paste0("No match for mutation ", this_mutation))
      who_pred = this_who_data %>%
        filter(MUTATION == this_mutation) %>%
        pull(PREDICTION) %>%
        head(1)
    
      this_pred_string = paste0(who_pred, ".X")
      pred_strings = c(pred_strings, this_pred_string)
      
      if (who_pred == "R"){
        this_x = this_who_data %>%
          filter(MUTATION == this_mutation) %>%
          pull(solo_R) %>%
        head(1)
        }
      if (who_pred == "S"){
        this_x = this_who_data %>%
          filter(MUTATION == this_mutation) %>%
          pull(solo_S) %>%
        head(1)
      }
      if (who_pred == "U"){
        this_x = this_who_data %>% 
          filter(MUTATION == this_mutation) %>% 
          mutate(choice = ifelse(as.numeric(solo_R) > as.numeric(solo_S), solo_R, solo_S)) %>%
          pull(choice)%>%
        head(1)
      } 
      if (is.na(this_x)){
        this_x = 0
      }
      this_y = 0
      x = c(x,this_x)
      y = c(y, this_y)
    }
  }
  
  this_df = as.data.frame(cbind(DRUG = rep(this_drug, length(pred_strings)), 
                          comparision = rep("WHOv2-v-training", length(pred_strings)),
                          MUTATION = mutation, 
                          MATCH = match, 
                          PREDICTION = pred_strings, 
                          x = as.numeric(as.character(x)), 
                          y =as.numeric(as.character(y))))

  fill_colors <- setNames(prediction_cols$colours, prediction_cols$pred_string)
  jit_lim = as.numeric(max(this_df$x))/20


  this_plot = this_df %>%
  filter(MATCH == TRUE) %>%
  ggplot(., aes(x = as.numeric(x), y = as.numeric(y))) +
    geom_jitter(aes(colour = PREDICTION),size = 3, alpha = 0.5, width = jit_lim, height = 0.5) +
    scale_shape_manual(values = c(16)) +
    scale_colour_manual(values = fill_colors) +
    labs(x = "WHOv1.2 isolate count", y = "training isolate count", colour = "WHOv1.2.training") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    guides(fill = guide_legend(title = "Prediction"), shape = guide_legend(title = "Match")) +
    theme_light() +
    ggtitle(this_drug_short) +   
      theme(plot.title = element_text(hjust = 0.5, size = 12))
  
  these_plots_match[[this_drug_short]] = this_plot
  
  this_plot = this_df %>%
  filter(MATCH == FALSE) %>%
  ggplot(., aes(x = as.numeric(x), y = as.numeric(y))) +
    geom_jitter(aes(colour = PREDICTION),size = 3, alpha = 0.5, width = jit_lim, height = 0.5) +
    scale_shape_manual(values = c(16)) +
    scale_colour_manual(values = fill_colors) +
    labs(x = "WHOv2 isolate count", y = "training isolate count", colour = "WHOv2.training") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    guides(fill = guide_legend(title = "Prediction"), shape = guide_legend(title = "Match")) +
    theme_light() +
    ggtitle(this_drug_short) +   
      theme(plot.title = element_text(hjust = 0.5, size = 12))
  
  these_plots_unmatch[[this_drug]] = this_plot
  
  # Filtering the resulting df to show mutations with evidence > 10
  this_top_df = this_df %>%
    filter(as.numeric(x) > 10) %>%
    arrange(desc(as.numeric(x)), PREDICTION) 
 
  this_top_df_who = rbind(this_top_df_who, this_top_df) 
}      

ggarrange(plotlist = these_plots_match[1:4])
ggarrange(plotlist = these_plots_match[5:8])
ggarrange(plotlist = these_plots_match[9:12])



top_table = as.data.frame.matrix(table(this_top_df_who$DRUG, this_top_df_who$PREDICTION)) %>% mutate(total_top_mutations = rowSums(.))
top_table$total_mutations = total_mutations
write.csv(top_table, file = "/Users/kmalone/macbook_m1_backup/github/cryptic-catalogue/data/training/results/catomatic_training/compare_top_whov2_to_training_FRS1.0.csv", quote=F, row.names=T)


this_top_df_who = this_top_df_who %>% 
  mutate(filt = as.numeric(x) + as.numeric(y))

# write.csv(this_top_df_who, file = "/Users/kmalone/macbook_m1_backup/github/cryptic-catalogue/data/training/results/compare_counts_top_whov2_to_training_FRS1.0.csv", quote=F, row.names=T)


```