---
title: "stats_inspection"
author: "Kerri M Malone"
date: "2024-06-12"
output: html_document
---
```{r setup, include=FALSE}


libs_load <- function(x){
  for( i in x ){
    print(paste0("Checking for library: ", i))
    if(require( i , character.only = TRUE ) ){
      print(paste0(i, " already installed. Loading now"))
    }
    #  require returns TRUE invisibly if it was able to load package
    if( ! require( i , character.only = TRUE ) ){
      print(paste0(i, " not installed. Trying CRAN for install."))
      #  If package was not able to be loaded then re-install
      install.packages( i , dependencies = TRUE )
      require( i , character.only = TRUE )
      paste0(i, " installed and loaded successfully")
    }
    if ( ! require(i, character.only=TRUE) ) {
      paste0(i," could not be installed from CRAN. Trying Bionconductor....")
      BiocManager::install(i)
      require( i , character.only = TRUE )
      paste0(i, " installed and loaded successfully")
    }
    if ( ! require(i, character.only=TRUE) ) {
      paste0(i, "could not be installed. Check manually")
    }
    #  Load package after installing
  }
}

#Load libraries
libs_load(c("data.table", "devtools",
            "chisq.posthoc.test","tidyverse", 
            "ggpubr", "gridExtra",
            "patchwork", "lme4"))

`%notin%` <- Negate(`%in%`)
```



```{r}

working_dir = "/Users/kmalone/macbook_m1_backup/github/cryptic-catalogue/data/training/results/catomatic_training"

stats_files = list.files(working_dir, 
                         pattern="_prediction_stats.csv", 
                         recursive = TRUE,
                         full.names = TRUE)


these_stat_plots = list()

for (this_file in stats_files){
  this_drug = str_split(basename(this_file), "_") %>% map_chr(4)
  
  print(paste0("On drug ", this_drug))
  
  this_data = fread(this_file, header=T)
  
  # Get total number of samples and scale #SU and #RU between 0-1
  this_data <- this_data %>%
  mutate(across(where(is.numeric), ~ ifelse(is.nan(.), 0, .))) %>%
  mutate(across(where(is.character), ~ str_replace_all(., "'NA'", "0"))) %>%
  mutate(across(where(is.character) & !all_of("DRUG"), as.numeric)) %>%
  rowwise() %>%
  mutate(total_samples = sum(c_across(`#RR`:`#SU`), na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(
    scaled_SU = if_else(!is.na(total_samples), `#SU` / total_samples, NA_real_),
    scaled_RU = if_else(!is.na(total_samples), `#RU` / total_samples, NA_real_)
  )

  
  # Convert numerical values to four decimal places
  this_data <- this_data %>%
      mutate(across(c(SENSITIVITY, SPECIFICITY, COVERAGE, scaled_SU, scaled_RU), ~ round(., 4)))
  
  # Summarise the data for plotting
  summary_table <- this_data %>%
      group_by(BACKGROUND_RATE, CI, FRS_PREDICT) %>%
      summarize(
          sensitivity = mean(SENSITIVITY),
          specificity = mean(SPECIFICITY),
          coverage = mean(COVERAGE),
          scaled_SU = mean(scaled_SU),
          scaled_RU = mean(scaled_RU)
      ) %>%
      gather(key = "Metric", 
             value = "Value", 
             sensitivity, specificity, coverage, scaled_SU, scaled_RU) %>%
      mutate(Facet_Label = ifelse(Metric == "sensitivity", "Sensitivity",
                                  ifelse(Metric == "specificity", "Specificity",
                                         ifelse(Metric == "coverage", "Coverage",
                                                ifelse(Metric == "scaled_SU", ".SU",
                                                       ifelse(Metric == "scaled_RU", ".RU", ""))))))
  
  
  this_out_file = str_replace(this_file, "stats.csv", "stats.pdf")
  # Plot and facet by FRS_PREDICT and CI
  this_plot = ggplot(summary_table, 
                     aes(x = factor(BACKGROUND_RATE), y = Value, 
                         colour = factor(FRS_PREDICT), group = factor(FRS_PREDICT))) +
      geom_point() +
      geom_line() +
      facet_grid(Facet_Label ~ CI, scales = "free_y") +
      labs(
          title = this_drug,
          x = "Background Rate",
          y = "Normalised Value",
          color = "Prediction FRS"
      ) +
      theme_light() +
      theme(
          strip.text = element_text(colour = "white", size=10),
          strip.background = element_rect(fill="grey50"),
          axis.text.x = element_text(angle = 90, hjust = 1)
      )

  ggsave(this_plot, filename=this_out_file, width=9.53, height = 6.53, limitsize = F)
  print("PDF saved")
  
  these_stat_plots[[this_drug]] = this_plot
  }

out_plots_file = "/Users/kmalone/macbook_m1_backup/github/cryptic-catalogue/data/training/results/catomatic_training/prediction_stats_all.pdf"

pdf(out_plots_file)

for (plot in these_stat_plots) {
  print(plot)
}

dev.off()

```


Choosing the best parameters for each drug using a grid search with custom scoring that prioritises sensitivity, specificity and coverage in that order
```{r}

working_dir = "/Users/kmalone/macbook_m1_backup/github/cryptic-catalogue/data/training/results/catomatic_training"

stats_files = list.files(working_dir, 
                         pattern="_prediction_stats.csv", 
                         recursive = TRUE,
                         full.names = TRUE)


list_of_chosen_parameters = list()

for (this_file in stats_files){
  this_drug = str_split(basename(this_file), "_") %>% map_chr(4)
  
  print(paste0("On drug ", this_drug))
  
  this_data = fread(this_file, header=T)

  #Deal with missingness  
  this_data <- this_data %>%
  mutate(across(where(is.numeric), ~ ifelse(is.nan(.), 0, .))) %>%
  mutate(across(where(is.character), ~ str_replace_all(., "'NA'", "0"))) %>%
  mutate(across(where(is.character) & !all_of("DRUG"), as.numeric)) 

  
  # Convert numerical values to four decimal places
  this_data <- this_data %>%
      mutate(across(c(SENSITIVITY, SPECIFICITY, COVERAGE), ~ round(., 4)))
  
  
  # Filter by coverage and specificity
  filtered_results <- this_data %>%
    filter(COVERAGE >= 0.8) %>%
    filter(SPECIFICITY >= 0.7) %>%
    select(DRUG, BACKGROUND_RATE, CI, SENSITIVITY, SPECIFICITY, COVERAGE )
  
  # Define a custom scoring function
  custom_score <- function(df) {
    df %>%
      arrange(desc(SENSITIVITY), desc(SPECIFICITY), desc(COVERAGE)) %>%
      slice(1)
  }
  
  # Find the best combination
  best_combination <-custom_score(filtered_results)
  
  list_of_chosen_parameters[[this_drug]] = best_combination
}

chosen_parameters = bind_rows(list_of_chosen_parameters)

write.csv(chosen_parameters, file="/Users/kmalone/macbook_m1_backup/github/cryptic-catalogue/data/training/results/catomatic_training/chosen_parameters_all_drugs.csv",
          quote=F,
          row.names = F)

```