---
title: "get_gene_panel_20240125"
author: "Kerri M Malone"
date: "2024-01-25"
output: html_document
---

```{r}
libs_load <- function(x){
  for( i in x ){
    print(paste0("Checking for library: ", i))
    if(require( i , character.only = TRUE ) ){
      print(paste0(i, " already installed. Loading now"))
    }
    #  require returns TRUE invisibly if it was able to load package
    if( ! require( i , character.only = TRUE ) ){
      print(paste0(i, " not installed. Trying CRAN for install."))
      #  If package was not able to be loaded then re-install
      install.packages( i , dependencies = TRUE )
      require( i , character.only = TRUE )
      paste0(i, " installed and loaded successfully")
    }
    if ( ! require(i, character.only=TRUE) ) {
      paste0(i," could not be installed from CRAN. Trying Bionconductor....")
      BiocManager::install(i)
      require( i , character.only = TRUE )
      paste0(i, " installed and loaded successfully")
    }
    if ( ! require(i, character.only=TRUE) ) {
      paste0(i, "Could not be installed. Check manually with github?")
    }
    #  Load package after installing
  }
}

#Load libraries
libs_load(c("tidyverse", 
            "data.table",
            "jsonlite",
            "readr",
            "UpSetR"))

`%notin%` <- Negate(`%in%`)

```

Getting a list of genes for building catalogue from mykrobe panel https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7004237/ 
https://figshare.com/articles/dataset/panel_final_tsv/7605395/1
```{r}
ROOTDIR = "cryptic-catalogue/"


panel = fromJSON(paste0(ROOTDIR,"data/variant_to_resistance_drug-202206.json"))

panel = imap_dfr(panel, ~ tibble(value = .x, name = .y))

panel_genes = panel %>%
  mutate(gene = str_split(name, "_") %>% map_chr(1)) %>%
  select(-name) %>%
  dplyr::rename("drug" = value) %>%
  distinct()

#Removing the top two entries as typo is present in mykrobe panel
panel_genes = panel_genes[3:nrow(panel_genes),]

panel_genes = panel_genes %>%
  arrange(drug)

#write_tsv(panel_genes, file = paste0(ROOTDIR, "data/gene_panel_20240125.tsv"))
```